export const whyYumfExistsContentFr = {
  slug: "why-yumf-exists",
  title: "Pourquoi Yumf existe",

  introduction: {
    title: "Chaque achat est un vote.",
    description:
      "Nous croyons que les plus grandes relations commencent souvent par un simple choix.",
  },

  sections: [
    {
      id: "each-purchase-is-a-vote",
      number: 1,
      title: "Chaque achat est un vote",
      paragraphs: [
        "Chaque jour, nous faisons des choix qui façonnent le monde qui nous entoure.",
        "Lorsque nous achetons un produit, nous faisons beaucoup plus qu’une simple transaction. Nous choisissons les entreprises que nous encourageons, les idées que nous soutenons et les façons de produire auxquelles nous accordons de la valeur.",
        "Nos achats influencent les produits qui continueront d’exister, les entreprises qui grandiront et celles qui disparaîtront peu à peu. Ils contribuent également à orienter l’innovation, les investissements et les modèles d’affaires de demain.",
        "Chaque achat est une décision qui dépasse largement le produit que nous rapportons à la maison. C’est un geste qui, répété des millions de fois chaque jour, façonne les marchés, les communautés et l’économie.",
      ],
      quote: {
        title: "Chaque achat est un vote.",
      },
      highlights: [
        "Un vote pour les entreprises que nous souhaitons voir grandir.",
        "Un vote pour les produits que nous voulons retrouver demain.",
        "Un vote pour les valeurs que nous choisissons d’encourager.",
        "Et, finalement, un vote pour le monde que nous voulons contribuer à construire.",
      ],
      conclusion: [
        "Pourtant, un vote n’a de véritable valeur que s’il peut produire des effets dans le temps.",
        "Or, une fois l’achat terminé, la relation entre le consommateur et l’entreprise qui a créé le produit s’interrompt souvent avant même d’avoir eu l’occasion de grandir.",
      ],
    },

    {
      id: "relationship-ends-too-soon",
      number: 2,
      title: "Une relation trop souvent interrompue",
      paragraphs: [
        "Nous aimerions croire que les meilleurs produits finissent toujours par trouver leur public.",
        "La réalité est plus complexe.",
        "Aujourd’hui, la visibilité constitue souvent la ressource la plus difficile à obtenir. Les entreprises qui disposent déjà d’une forte présence sur le marché, de réseaux de distribution établis ou de budgets marketing importants bénéficient naturellement d’un avantage considérable pour attirer et conserver l’attention des consommateurs.",
        "À l’inverse, de nombreux produits remarquables demeurent largement inconnus, non pas parce qu’ils manquent de qualité, mais parce qu’ils disposent de moins d’occasions d’être découverts.",
        "Pourtant, la difficulté ne s’arrête pas là.",
        "Même lorsqu’un consommateur découvre un produit qu’il apprécie, quelque chose d’étonnant se produit.",
        "Le produit poursuit sa route.",
        "Le consommateur poursuit la sienne.",
        "Mais la relation entre celui qui a créé le produit et celui qui l’a choisi s’interrompt presque toujours.",
        "Une fois l’achat terminé, le fabricant ignore généralement qui vient de lui accorder sa confiance.",
        "Il ne peut remercier cette personne.",
        "Il ne peut lui faire découvrir ses nouveautés.",
        "Il ne peut poursuivre la relation qui vient pourtant de naître.",
        "Le consommateur, de son côté, conserve parfois un excellent souvenir de cette découverte.",
        "Puis d’autres achats surviennent.",
        "D’autres produits attirent son attention.",
        "Progressivement, cette relation s’efface.",
        "Ce phénomène ne résulte ni d’un manque de volonté des consommateurs, ni d’un manque de qualité des produits.",
        "Il ne résulte pas davantage d’un manque d’engagement des fabricants.",
        "Il découle simplement de la manière dont notre système commercial s’est construit.",
        "Ce système est remarquablement efficace pour permettre aux consommateurs de découvrir, comparer et acheter des produits.",
        "Il l’est beaucoup moins lorsqu’il s’agit de permettre aux fabricants de prolonger la relation avec les personnes qui choisissent leurs produits.",
      ],
      conclusion: [
        "Autrement dit, le véritable enjeu n’est pas seulement de favoriser la découverte.",
        "Il consiste à permettre à cette découverte de devenir une relation durable.",
      ],
    },

    {
      id: "manufacturer-paradox",
      number: 3,
      title: "Le paradoxe des fabricants indépendants",
      paragraphs: [
        "Partout, des femmes et des hommes consacrent leur énergie à imaginer, fabriquer et améliorer des produits dont ils sont fiers.",
        "Ils innovent.",
        "Ils expérimentent.",
        "Ils recherchent des ingrédients de qualité.",
        "Ils perfectionnent leurs procédés.",
        "Ils développent de nouvelles saveurs.",
        "Ils prennent des risques pour proposer quelque chose de différent.",
        "Certaines entreprises sont profondément enracinées dans leur communauté.",
        "Elles créent des emplois.",
        "Elles collaborent avec des partenaires locaux.",
        "Elles contribuent à la vitalité économique de leur région.",
        "D’autres se distinguent par leur savoir-faire, leur créativité ou leur capacité d’innover.",
        "Lorsqu’un consommateur découvre l’un de leurs produits et l’apprécie, tout semble réuni pour qu’une relation puisse naître.",
        "Pourtant, c’est souvent l’inverse qui se produit.",
        "Une fois le produit acheté, le fabricant ignore généralement qui vient de lui accorder sa confiance.",
        "Il ne peut remercier cette personne.",
        "Il ne peut lui faire découvrir ses nouveautés.",
        "Il ne peut comprendre ses attentes.",
        "Il ne peut poursuivre naturellement cette relation.",
        "Le consommateur, de son côté, conserve parfois un excellent souvenir de cette découverte.",
        "Mais, faute de lien direct, cette relation s’estompe progressivement parmi les centaines d’autres décisions d’achat qui suivront.",
        "Ainsi apparaît un paradoxe.",
        "Les fabricants consacrent des années à créer des produits capables de susciter la confiance.",
        "Mais, lorsque cette confiance se manifeste enfin par un achat, ils disposent rarement d’un moyen naturel pour la faire grandir.",
      ],
      conclusion: [
        "Ce n’est pas la relation qui manque.",
        "C’est l’espace où cette relation pourrait continuer d’exister.",
      ],
    },

    {
      id: "consumers-seek-relationship",
      number: 4,
      title: "Les consommateurs cherchent aussi cette relation",
      paragraphs: [
        "Les consommateurs d’aujourd’hui ne recherchent pas uniquement un produit.",
        "Ils recherchent également une histoire.",
        "Une qualité.",
        "Une authenticité.",
        "Une relation de confiance avec les entreprises qu’ils choisissent.",
        "Ils aiment découvrir de nouvelles entreprises.",
        "Encourager des fabricants qui partagent leurs valeurs.",
        "Retrouver les produits qu’ils apprécient.",
        "Comprendre ce qui distingue les entreprises auxquelles ils accordent leur confiance.",
        "Lorsqu’une découverte les enthousiasme, ils souhaitent souvent qu’elle puisse se poursuivre.",
        "Découvrir les nouveautés du fabricant.",
        "Mieux connaître son histoire.",
        "Continuer à l’encourager au fil du temps.",
        "Pourtant, cette continuité demeure rarement possible.",
        "Après l’achat, le fabricant disparaît derrière les étagères du commerce où le produit a été découvert.",
        "Les échanges cessent.",
        "Les nouveautés passent inaperçues.",
        "La relation s’interrompt avant d’avoir réellement commencé.",
        "Ce n’est pas parce que les consommateurs ne souhaitent pas poursuivre cette relation.",
        "Ce n’est pas davantage parce que les fabricants n’en voient pas la valeur.",
        "C’est parce que le système actuel n’a jamais été conçu pour permettre à cette relation de durer.",
        "Le consommateur conserve sa liberté de choisir où il achète.",
        "Le détaillant continue de jouer son rôle de découverte et de distribution.",
        "Le fabricant continue de créer des produits.",
        "Mais entre le fabricant et les personnes qui choisissent ses produits, il manque encore un espace où cette relation puisse naturellement grandir.",
      ],
      conclusion: [
        "C’est précisément cette absence qui explique pourquoi tant de belles découvertes demeurent sans lendemain.",
      ],
    },

    {
      id: "not-a-willpower-problem",
      number: 5,
      title: "Ce n’est pas un problème de volonté",
      paragraphs: [
        "Il serait facile de croire que cette situation existe parce que les consommateurs ne sont pas suffisamment fidèles.",
        "Ou parce que les fabricants ne communiquent pas assez.",
        "Ou encore parce que les détaillants privilégient certains produits plutôt que d’autres.",
        "Nous ne le croyons pas.",
        "Le consommateur n’est pas le problème.",
        "Le fabricant n’est pas le problème.",
        "Le détaillant n’est pas le problème.",
        "Chacun remplit le rôle qui lui revient.",
        "Les consommateurs découvrent et choisissent librement les produits qu’ils souhaitent acheter.",
        "Les détaillants rendent ces produits accessibles et facilitent leur comparaison.",
        "Les fabricants imaginent, produisent et améliorent continuellement ce qu’ils offrent.",
        "Le système fonctionne exactement comme il a été conçu.",
        "Il permet aux produits de circuler efficacement entre les fabricants, les détaillants et les consommateurs.",
        "Mais il présente une limite importante.",
        "Une fois l’achat terminé, il ne prévoit aucun espace où la relation entre le fabricant et les personnes qui choisissent ses produits puisse naturellement se poursuivre.",
        "Autrement dit, ce qui manque n’est pas de la bonne volonté.",
        "Ce qui manque, c’est une infrastructure capable de permettre à cette relation d’exister.",
        "Une infrastructure qui ne remplace ni le détaillant ni les habitudes d’achat des consommateurs.",
        "Une infrastructure qui complète simplement l’écosystème existant en donnant enfin aux fabricants un espace relationnel durable.",
      ],
      conclusion: [
        "C’est précisément cette absence que nous avons choisi d’explorer.",
      ],
    },

    {
      id: "our-conviction",
      number: 6,
      title: "Notre conviction",
      paragraphs: [
        "Nous croyons qu’une autre approche est possible.",
        "Nous croyons que les entreprises qui créent des produits remarquables devraient pouvoir développer une relation durable avec les personnes qui les choisissent.",
        "Nous croyons que les consommateurs souhaitent pouvoir retrouver les fabricants qu’ils apprécient, découvrir leurs nouveautés et continuer à les encourager au fil du temps.",
        "Nous croyons qu’un achat ne devrait jamais être la fin d’une relation.",
        "Il devrait en être le commencement.",
        "Mais surtout, nous croyons qu’il manque aujourd’hui un élément essentiel dans l’écosystème du commerce de détail.",
        "Le détaillant dispose déjà de son espace relationnel avec ses clients.",
        "Les entreprises de services disposent de leurs programmes de fidélisation.",
        "Les consommateurs disposent de nombreux moyens de découvrir, comparer et recommander les produits qu’ils apprécient.",
        "Les fabricants de produits de consommation, eux, ne disposent généralement d’aucune infrastructure leur permettant de prolonger naturellement la relation avec les personnes qui choisissent leurs produits.",
        "C’est cette infrastructure relationnelle que nous croyons nécessaire.",
        "Non pas pour remplacer les détaillants.",
        "Non pas pour modifier la façon dont les consommateurs achètent.",
        "Mais pour permettre à une relation qui existe déjà au moment de l’achat de continuer à grandir dans le temps.",
        "Cette conviction guide chacune de nos décisions.",
        "Elle inspire la manière dont nous concevons Yumf.",
      ],
      conclusion: [
        "Non pas comme un programme de fidélisation de plus.",
        "Mais comme l’infrastructure relationnelle qui manquait aux fabricants de produits de consommation.",
      ],
    },

    {
      id: "our-mission",
      number: 7,
      title: "Notre mission",
      paragraphs: [
        "Nous croyons que chaque achat peut devenir le début d’une relation durable.",
        "Notre mission consiste à rendre cette relation possible.",
        "Yumf a pour vocation de devenir cet espace relationnel durable permettant aux fabricants de produits de consommation de retrouver les personnes qui choisissent leurs produits et de continuer à développer cette relation au fil du temps.",
        "Cette mission guide chacune de nos décisions.",
        "Elle inspire la manière dont nous concevons nos Services, les choix que nous faisons et l’évolution de notre Plateforme.",
        "Nous ne cherchons pas à remplacer les détaillants.",
        "Nous ne cherchons pas à modifier les habitudes d’achat des consommateurs.",
        "Nous cherchons à compléter un écosystème qui fonctionne déjà en permettant à une relation, jusqu’ici interrompue au moment de l’achat, de continuer naturellement d’exister.",
        "Notre ambition dépasse ainsi le cadre de la fidélisation traditionnelle.",
      ],
      conclusion: [
        "Nous voulons contribuer à un écosystème où les fabricants peuvent construire une communauté autour de leurs produits et où les consommateurs peuvent continuer à encourager les entreprises auxquelles ils choisissent d’accorder leur confiance.",
      ],
    },

    {
      id: "what-it-means",
      number: 8,
      title: "Ce que cela signifie",
      paragraphs: [
        "Si Yumf constitue ce fondement relationnel, alors chacune de ses composantes trouve naturellement sa place.",
        "Les Clubs ne sont pas des programmes de fidélité.",
        "Ils deviennent les espaces permanents où un fabricant peut retrouver les personnes qui choisissent ses produits et faire grandir cette relation au fil du temps.",
        "Les Programmes ne constituent plus le cœur du système.",
        "Ils deviennent différentes façons d’animer cette relation selon les objectifs, les saisons, les lancements ou les initiatives propres à chaque fabricant.",
        "Les Produits participants représentent le point de départ de cette relation.",
        "Chaque achat admissible devient une occasion de reconnaître la confiance qu’un consommateur accorde à un fabricant.",
        "Les Récompenses ne servent plus uniquement à encourager un prochain achat.",
        "Elles deviennent une manière de remercier les consommateurs pour une relation qui se construit dans le temps.",
        "Les Données de fidélité ne sont plus de simples statistiques.",
        "Elles deviennent la mémoire vivante de cette relation.",
        "Elles permettent de mieux comprendre les consommateurs, de reconnaître leur engagement et d’aider les fabricants à continuer d’innover en restant proches des personnes qui choisissent leurs produits.",
        "Ainsi, rien dans Yumf n’a été imaginé comme une fonctionnalité isolée.",
        "Chaque composante répond à une même ambition.",
        "Permettre à une relation qui naît naturellement au moment d’un achat de continuer à grandir bien après celui-ci.",
        "Lorsqu’on regarde Yumf sous cet angle, les Clubs, les Programmes, les Produits participants, les Récompenses et les Données de fidélité cessent d’être des éléments indépendants.",
      ],
      conclusion: [
        "Ils deviennent les différentes expressions d’une même infrastructure relationnelle.",
      ],
    },

    {
      id: "our-ambition",
      number: 9,
      title: "Notre ambition",
      paragraphs: [
        "Nous savons que Yumf ne transformera pas, à lui seul, la façon dont le monde consomme.",
        "Mais nous croyons qu’il est possible de contribuer à une évolution importante.",
        "Une évolution où les fabricants de produits de consommation disposent enfin d’un espace leur permettant de construire une relation durable avec les personnes qui choisissent leurs produits.",
        "Une évolution où les consommateurs peuvent retrouver les entreprises auxquelles ils accordent leur confiance, découvrir leurs nouveautés et continuer à les encourager au fil du temps.",
        "Une évolution où les détaillants continuent de jouer pleinement leur rôle de découverte, de comparaison et de distribution, tandis que les fabricants peuvent enfin prolonger naturellement la relation née de cette découverte.",
        "Nous ne cherchons pas à remplacer les modèles qui existent déjà.",
        "Nous cherchons à compléter un écosystème qui fonctionne en lui apportant ce qui lui manque encore.",
        "Un espace où la relation entre un fabricant et les consommateurs qui choisissent ses produits peut continuer de grandir.",
        "Nous croyons que cette évolution bénéficiera à tous.",
        "Aux consommateurs, qui pourront conserver un lien avec les entreprises qu’ils apprécient.",
        "Aux fabricants, qui pourront mieux comprendre leur communauté et continuer à innover à ses côtés.",
        "Aux détaillants, qui continueront d’offrir les lieux privilégiés de la découverte et de l’achat.",
        "Et, plus largement, à un écosystème où la fidélité ne sera plus seulement mesurée par les transactions qu’il génère, mais aussi par les relations qu’il permet de construire.",
      ],
      conclusion: [
        "Parce qu’au fond, nous croyons qu’un achat ne devrait jamais marquer la fin d’une histoire.",
        "Il devrait être le premier chapitre d’une relation appelée à grandir.",
      ],
    },
  ],
} as const;
